<?php
$paramsLocal = __DIR__ . '/params-local.php';
$commonParamsLocal = __DIR__ . '/../../common/config/params-local.php';

$params = \yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/../../common/config/params.php',
    is_file($commonParamsLocal) ? require $commonParamsLocal : [],
    require __DIR__ . '/params.php',
    is_file($paramsLocal) ? require $paramsLocal : []
);

use \yii\web\Request;
$baseUrl = str_replace('/frontend/web', '', (new Request)->getBaseUrl());

return [
    'id' => 'bioenlace-frontend',
    'language' => 'es',
    'homeUrl' => ['/site/index'],
    'defaultRoute' => 'site/index',
    'basePath' => dirname(__DIR__),
    'bootstrap' => [
        'log',
        \common\components\Platform\Core\Db\EnsureDbConnectionBootstrap::class,
        \frontend\components\EnforceGhostAccessBootstrap::class,
    ],
    'timeZone' => 'America/Argentina/Tucuman',
    'controllerNamespace' => 'frontend\controllers',    
    'components' => [
        'formatter' => [
            'dateFormat' => 'dd/MM/yyyy',
            'datetimeFormat' => 'php:F jS, Y h:i',
            'timeFormat' => 'php:H:i:s',
            'defaultTimeZone' => 'America/Argentina/Tucuman',
        ],
        'request' => [
            'csrfParam' => '_csrf-frontend',
            'baseUrl' => $baseUrl,
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ]
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'errorHandler' => [
            'errorAction' => 'site/error'
        ],        
        'authManager' => [
            'class' => 'common\models\BioenlaceDbManager',
            'efectorAssignmentTable' => 'profesional_efector_servicio',
            'rolesEspeciales' => ['_x_efector_', '_sin_efector_'],
        ],
        'user' => [
            'class' => 'frontend\components\UserConfig',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-bioenlace-frontend', 'httpOnly' => true],            
            // Comment this if you don't want to record user logins
            'on afterLogin' => function ($event) {
                \common\models\UserVisitLog::newVisitor($event->identity->id);
                \frontend\controllers\SiteController::despuesDeLogin();
            },
        ],
        'session' => [
            // this is the name of the session cookie used for login on the frontend
            'name' => 'bioenlace-frontend',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['warning'],
                ],
                [
                    'class' => \common\components\Platform\Infra\Log\ResilientDbTarget::class,
                    'levels' => ['error'],
                ],
            ],
        ],    
        'urlManager' => [
            'class' => 'yii\web\UrlManager',
            // Disable index.php
            'showScriptName' => false,
            // Disable r= routes
            'enablePrettyUrl' => true,
            'rules' => [
                'site/login' => 'auth/login',
                'login' => 'auth/login',
                'user-management/auth/login' => 'auth/login',
                'user-management/auth/logout' => 'auth/logout',
                'user-management/auth/change-own-password' => 'auth/change-own-password',
                'user-management/auth/password-recovery' => 'auth/password-recovery',
                'user-management/auth/password-recovery-receive/<token:[\w\-]+>' => 'auth/password-recovery-receive',
                'user-management/auth/activate-account' => 'auth/activate-account',
                'user-management/auth/activate-account-receive/<token:[\w\-]+>' => 'auth/activate-account-receive',
                'user-management/auth/confirm-email' => 'auth/confirm-email',
                'user-management/auth/confirm-email-receive/<token:[\w\-]+>' => 'auth/confirm-email-receive',
                'turno/resolucion/<token:[\w\.\-\_=]+>' => 'turno-public/resolucion',
                'site/inicio' => 'site/sesion-operativa',
                'site/establecer-session-final' => 'site/establecer-sesion-final',
                'site/session-efector-redireccionar' => 'site/sesion-operativa',
                '<controller:\w+>/<id:\d+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
                // Asistente (canal chat)
                'GET api/<version:\w+>/asistente/estado' => '<version>/chat/estado',
                'OPTIONS api/<version:\w+>/asistente/estado' => '<version>/chat/estado',
                'POST api/<version:\w+>/asistente/enviar' => '<version>/chat/recibir',
                'OPTIONS api/<version:\w+>/asistente/enviar' => '<version>/chat/recibir',

                // Preflight CORS genérico (evita declarar OPTIONS por endpoint)
                'OPTIONS api/<version:\w+>/<controller:[\\w-]+>' => '<version>/<controller>/options',
                'OPTIONS api/<version:\w+>/<controller:[\\w-]+>/<action:[\\w-]+>' => '<version>/<controller>/options',
                // API clínica FHIR (Encounter, CarePlan, Condition)
                'POST api/<version:\w+>/clinical/encounter/analizar' => '<version>/clinical/encounter/analizar',
                'OPTIONS api/<version:\w+>/clinical/encounter/analizar' => '<version>/clinical/encounter/analizar',
                'POST api/<version:\w+>/clinical/encounter/guardar' => '<version>/clinical/encounter/guardar',
                'OPTIONS api/<version:\w+>/clinical/encounter/guardar' => '<version>/clinical/encounter/guardar',
                'GET api/<version:\w+>/clinical/encounter/listar-ordenes-activas' => '<version>/clinical/encounter/listar-ordenes-activas',
                'OPTIONS api/<version:\w+>/clinical/encounter/listar-ordenes-activas' => '<version>/clinical/encounter/listar-ordenes-activas',
                'GET api/<version:\w+>/clinical/encounter/listar-atenciones-como-paciente' => '<version>/clinical/encounter-patient-summary/listar-atenciones-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/encounter/listar-atenciones-como-paciente' => '<version>/clinical/encounter-patient-summary/listar-atenciones-como-paciente',
                'GET api/<version:\w+>/clinical/encounter/ver-resumen-como-paciente' => '<version>/clinical/encounter-patient-summary/ver-resumen-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/encounter/ver-resumen-como-paciente' => '<version>/clinical/encounter-patient-summary/ver-resumen-como-paciente',
                'GET api/<version:\w+>/clinical/encounter/ultima-atencion-como-paciente' => '<version>/clinical/encounter-patient-summary/ultima-atencion-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/encounter/ultima-atencion-como-paciente' => '<version>/clinical/encounter-patient-summary/ultima-atencion-como-paciente',
                'GET api/<version:\w+>/clinical/encounter/mis-atenciones-como-paciente' => '<version>/clinical/encounter-patient-summary/mis-atenciones-como-paciente',
                'POST api/<version:\w+>/clinical/encounter/mis-atenciones-como-paciente' => '<version>/clinical/encounter-patient-summary/mis-atenciones-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/encounter/mis-atenciones-como-paciente' => '<version>/clinical/encounter-patient-summary/mis-atenciones-como-paciente',
                'GET api/<version:\w+>/clinical/encounter/ver-resumen-atencion-como-paciente' => '<version>/clinical/encounter-patient-summary/ver-resumen-atencion-como-paciente',
                'POST api/<version:\w+>/clinical/encounter/ver-resumen-atencion-como-paciente' => '<version>/clinical/encounter-patient-summary/ver-resumen-atencion-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/encounter/ver-resumen-atencion-como-paciente' => '<version>/clinical/encounter-patient-summary/ver-resumen-atencion-como-paciente',
                'GET api/<version:\w+>/clinical/encounter/ultima-atencion-ui-como-paciente' => '<version>/clinical/encounter-patient-summary/ultima-atencion-ui-como-paciente',
                'POST api/<version:\w+>/clinical/encounter/ultima-atencion-ui-como-paciente' => '<version>/clinical/encounter-patient-summary/ultima-atencion-ui-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/encounter/ultima-atencion-ui-como-paciente' => '<version>/clinical/encounter-patient-summary/ultima-atencion-ui-como-paciente',
                'POST api/<version:\w+>/clinical/legal-record-export/solicitar' => '<version>/clinical/legal-record-export/solicitar',
                'OPTIONS api/<version:\w+>/clinical/legal-record-export/solicitar' => '<version>/clinical/legal-record-export/solicitar',
                'GET api/<version:\w+>/clinical/legal-record-export/listar-mis-solicitudes' => '<version>/clinical/legal-record-export/listar-mis-solicitudes',
                'OPTIONS api/<version:\w+>/clinical/legal-record-export/listar-mis-solicitudes' => '<version>/clinical/legal-record-export/listar-mis-solicitudes',
                'GET api/<version:\w+>/clinical/legal-record-export/ver-estado' => '<version>/clinical/legal-record-export/ver-estado',
                'OPTIONS api/<version:\w+>/clinical/legal-record-export/ver-estado' => '<version>/clinical/legal-record-export/ver-estado',
                'GET api/<version:\w+>/clinical/legal-record-export/descargar' => '<version>/clinical/legal-record-export/descargar',
                'OPTIONS api/<version:\w+>/clinical/legal-record-export/descargar' => '<version>/clinical/legal-record-export/descargar',

                // Export FHIR historia clínica (estado jobs staff)
                'GET api/<version:\w+>/clinical/history-exchange/listar-por-encounter' => '<version>/clinical/history-exchange/listar-por-encounter',
                'OPTIONS api/<version:\w+>/clinical/history-exchange/listar-por-encounter' => '<version>/clinical/history-exchange/listar-por-encounter',
                'GET api/<version:\w+>/clinical/history-exchange/ver-estado' => '<version>/clinical/history-exchange/ver-estado',
                'OPTIONS api/<version:\w+>/clinical/history-exchange/ver-estado' => '<version>/clinical/history-exchange/ver-estado',
                'POST api/<version:\w+>/clinical/emergency-guardia/ingresar' => '<version>/clinical/emergency-guardia/ingresar',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/ingresar' => '<version>/clinical/emergency-guardia/ingresar',
                'POST api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/registrar-triage' => '<version>/clinical/emergency-guardia/registrar-triage',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/registrar-triage' => '<version>/clinical/emergency-guardia/registrar-triage',
                'GET api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/ver' => '<version>/clinical/emergency-guardia/ver',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/ver' => '<version>/clinical/emergency-guardia/ver',
                'GET api/<version:\w+>/clinical/emergency-guardia/indicadores-resumen' => '<version>/clinical/emergency-guardia/indicadores-resumen',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/indicadores-resumen' => '<version>/clinical/emergency-guardia/indicadores-resumen',
                'GET api/<version:\w+>/clinical/emergency-guardia/listar-efectores-derivacion' => '<version>/clinical/emergency-guardia/listar-efectores-derivacion',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/listar-efectores-derivacion' => '<version>/clinical/emergency-guardia/listar-efectores-derivacion',
                'POST api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/asignar' => '<version>/clinical/emergency-guardia/asignar',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/asignar' => '<version>/clinical/emergency-guardia/asignar',
                'POST api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/iniciar-atencion' => '<version>/clinical/emergency-guardia/iniciar-atencion',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/iniciar-atencion' => '<version>/clinical/emergency-guardia/iniciar-atencion',
                'POST api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/derivar' => '<version>/clinical/emergency-guardia/derivar',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/derivar' => '<version>/clinical/emergency-guardia/derivar',
                'POST api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/finalizar' => '<version>/clinical/emergency-guardia/finalizar',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/finalizar' => '<version>/clinical/emergency-guardia/finalizar',
                'GET api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/resumen-clinico' => '<version>/clinical/emergency-guardia/resumen-clinico',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/resumen-clinico' => '<version>/clinical/emergency-guardia/resumen-clinico',
                'POST api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/crear-pedido' => '<version>/clinical/emergency-guardia/crear-pedido',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/crear-pedido' => '<version>/clinical/emergency-guardia/crear-pedido',
                'POST api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/solicitar-internacion' => '<version>/clinical/emergency-guardia/solicitar-internacion',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/<guardiaId:\d+>/solicitar-internacion' => '<version>/clinical/emergency-guardia/solicitar-internacion',
                'GET api/<version:\w+>/clinical/emergency-guardia/indicadores-export-csv' => '<version>/clinical/emergency-guardia/indicadores-export-csv',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/indicadores-export-csv' => '<version>/clinical/emergency-guardia/indicadores-export-csv',
                'GET api/<version:\w+>/clinical/emergency-guardia/sla-config' => '<version>/clinical/emergency-guardia/sla-config',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/sla-config' => '<version>/clinical/emergency-guardia/sla-config',
                'GET api/<version:\w+>/clinical/emergency-guardia/elegir-paciente-triage' => '<version>/clinical/emergency-guardia/elegir-paciente-triage',
                'POST api/<version:\w+>/clinical/emergency-guardia/elegir-paciente-triage' => '<version>/clinical/emergency-guardia/elegir-paciente-triage',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/elegir-paciente-triage' => '<version>/clinical/emergency-guardia/elegir-paciente-triage',
                'GET api/<version:\w+>/clinical/emergency-guardia/registrar-triage-formulario' => '<version>/clinical/emergency-guardia/registrar-triage-formulario',
                'POST api/<version:\w+>/clinical/emergency-guardia/registrar-triage-formulario' => '<version>/clinical/emergency-guardia/registrar-triage-formulario',
                'OPTIONS api/<version:\w+>/clinical/emergency-guardia/registrar-triage-formulario' => '<version>/clinical/emergency-guardia/registrar-triage-formulario',
                'GET api/<version:\w+>/clinical/care-plan/ver-tratamiento-paciente' => '<version>/clinical/care-plan/ver-tratamiento-paciente',
                'OPTIONS api/<version:\w+>/clinical/care-plan/ver-tratamiento-paciente' => '<version>/clinical/care-plan/ver-tratamiento-paciente',
                'GET api/<version:\w+>/clinical/care-plans/adherencia-resumen-staff' => '<version>/clinical/care-plan/adherencia-resumen-staff',
                'OPTIONS api/<version:\w+>/clinical/care-plans/adherencia-resumen-staff' => '<version>/clinical/care-plan/adherencia-resumen-staff',
                'GET api/<version:\w+>/clinical/internacion/mapa-camas' => '<version>/clinical/internacion/mapa-camas',
                'POST api/<version:\w+>/clinical/internacion/mapa-camas' => '<version>/clinical/internacion/mapa-camas',
                'OPTIONS api/<version:\w+>/clinical/internacion/mapa-camas' => '<version>/clinical/internacion/mapa-camas',
                'GET api/<version:\w+>/clinical/internacion/indicadores-resumen' => '<version>/clinical/internacion/indicadores-resumen',
                'OPTIONS api/<version:\w+>/clinical/internacion/indicadores-resumen' => '<version>/clinical/internacion/indicadores-resumen',
                'POST api/<version:\w+>/clinical/internacion/cama/<camaId:\d+>/marcar-estado' => '<version>/clinical/internacion/marcar-estado',
                'OPTIONS api/<version:\w+>/clinical/internacion/cama/<camaId:\d+>/marcar-estado' => '<version>/clinical/internacion/marcar-estado',
                'GET api/<version:\w+>/clinical/internacion/<internacionId:\d+>/alta-formulario' => '<version>/clinical/internacion/alta-formulario',
                'POST api/<version:\w+>/clinical/internacion/<internacionId:\d+>/alta-formulario' => '<version>/clinical/internacion/alta-formulario',
                'OPTIONS api/<version:\w+>/clinical/internacion/<internacionId:\d+>/alta-formulario' => '<version>/clinical/internacion/alta-formulario',
                'GET api/<version:\w+>/clinical/internacion/<internacionId:\d+>/cambio-cama-formulario' => '<version>/clinical/internacion/cambio-cama-formulario',
                'POST api/<version:\w+>/clinical/internacion/<internacionId:\d+>/cambio-cama-formulario' => '<version>/clinical/internacion/cambio-cama-formulario',
                'OPTIONS api/<version:\w+>/clinical/internacion/<internacionId:\d+>/cambio-cama-formulario' => '<version>/clinical/internacion/cambio-cama-formulario',
                'GET api/<version:\w+>/clinical/internacion/ingreso-formulario' => '<version>/clinical/internacion/ingreso-formulario',
                'POST api/<version:\w+>/clinical/internacion/ingreso-formulario' => '<version>/clinical/internacion/ingreso-formulario',
                'OPTIONS api/<version:\w+>/clinical/internacion/ingreso-formulario' => '<version>/clinical/internacion/ingreso-formulario',
                'GET api/<version:\w+>/clinical/internacion/plantillas-epicrisis' => '<version>/clinical/internacion/plantillas-epicrisis',
                'OPTIONS api/<version:\w+>/clinical/internacion/plantillas-epicrisis' => '<version>/clinical/internacion/plantillas-epicrisis',
                'GET api/<version:\w+>/clinical/internacion/<internacionId:\d+>/preview-plantilla-epicrisis' => '<version>/clinical/internacion/preview-plantilla-epicrisis',
                'OPTIONS api/<version:\w+>/clinical/internacion/<internacionId:\d+>/preview-plantilla-epicrisis' => '<version>/clinical/internacion/preview-plantilla-epicrisis',
                'GET api/<version:\w+>/clinical/internacion-epicrisis-plantilla/listar-admin' => '<version>/clinical/internacion-epicrisis-plantilla/listar-admin',
                'OPTIONS api/<version:\w+>/clinical/internacion-epicrisis-plantilla/listar-admin' => '<version>/clinical/internacion-epicrisis-plantilla/listar-admin',
                'GET api/<version:\w+>/clinical/internacion-epicrisis-plantilla/ver/<id:\d+>' => '<version>/clinical/internacion-epicrisis-plantilla/ver',
                'OPTIONS api/<version:\w+>/clinical/internacion-epicrisis-plantilla/ver/<id:\d+>' => '<version>/clinical/internacion-epicrisis-plantilla/ver',
                'POST api/<version:\w+>/clinical/internacion-epicrisis-plantilla/crear' => '<version>/clinical/internacion-epicrisis-plantilla/crear',
                'OPTIONS api/<version:\w+>/clinical/internacion-epicrisis-plantilla/crear' => '<version>/clinical/internacion-epicrisis-plantilla/crear',
                'PUT api/<version:\w+>/clinical/internacion-epicrisis-plantilla/actualizar/<id:\d+>' => '<version>/clinical/internacion-epicrisis-plantilla/actualizar',
                'PATCH api/<version:\w+>/clinical/internacion-epicrisis-plantilla/actualizar/<id:\d+>' => '<version>/clinical/internacion-epicrisis-plantilla/actualizar',
                'OPTIONS api/<version:\w+>/clinical/internacion-epicrisis-plantilla/actualizar/<id:\d+>' => '<version>/clinical/internacion-epicrisis-plantilla/actualizar',
                'POST api/<version:\w+>/clinical/internacion-epicrisis-plantilla/desactivar/<id:\d+>' => '<version>/clinical/internacion-epicrisis-plantilla/desactivar',
                'OPTIONS api/<version:\w+>/clinical/internacion-epicrisis-plantilla/desactivar/<id:\d+>' => '<version>/clinical/internacion-epicrisis-plantilla/desactivar',
                'POST api/<version:\w+>/clinical/internacion-epicrisis-plantilla/activar/<id:\d+>' => '<version>/clinical/internacion-epicrisis-plantilla/activar',
                'OPTIONS api/<version:\w+>/clinical/internacion-epicrisis-plantilla/activar/<id:\d+>' => '<version>/clinical/internacion-epicrisis-plantilla/activar',
                'GET api/<version:\w+>/clinical/encounter/<encounterId:\d+>/conditions' => '<version>/clinical/condition/index',
                'OPTIONS api/<version:\w+>/clinical/encounter/<encounterId:\d+>/conditions' => '<version>/clinical/condition/index',
                'GET api/<version:\w+>/clinical/encounter/<encounterId:\d+>/medication-requests' => '<version>/clinical/medication-request/index',
                'OPTIONS api/<version:\w+>/clinical/encounter/<encounterId:\d+>/medication-requests' => '<version>/clinical/medication-request/index',
                'POST api/<version:\w+>/clinical/encounter/<encounterId:\d+>/medication-requests' => '<version>/clinical/medication-request/create',
                'POST api/<version:\w+>/clinical/encounter/<encounterId:\d+>/electronic-prescription/crear-borrador' => '<version>/clinical/electronic-prescription/crear-borrador',
                'OPTIONS api/<version:\w+>/clinical/encounter/<encounterId:\d+>/electronic-prescription/crear-borrador' => '<version>/clinical/electronic-prescription/crear-borrador',
                'GET api/<version:\w+>/clinical/encounter/<encounterId:\d+>/electronic-prescriptions' => '<version>/clinical/electronic-prescription/por-encounter',
                'OPTIONS api/<version:\w+>/clinical/encounter/<encounterId:\d+>/electronic-prescriptions' => '<version>/clinical/electronic-prescription/por-encounter',
                'GET api/<version:\w+>/clinical/electronic-prescription/mis-recetas-como-paciente' => '<version>/clinical/electronic-prescription/mis-recetas-como-paciente',
                'POST api/<version:\w+>/clinical/electronic-prescription/mis-recetas-como-paciente' => '<version>/clinical/electronic-prescription/mis-recetas-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/electronic-prescription/mis-recetas-como-paciente' => '<version>/clinical/electronic-prescription/mis-recetas-como-paciente',
                'GET api/<version:\w+>/clinical/electronic-prescription/ver-receta-como-paciente' => '<version>/clinical/electronic-prescription/ver-receta-como-paciente',
                'POST api/<version:\w+>/clinical/electronic-prescription/ver-receta-como-paciente' => '<version>/clinical/electronic-prescription/ver-receta-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/electronic-prescription/ver-receta-como-paciente' => '<version>/clinical/electronic-prescription/ver-receta-como-paciente',
                'GET api/<version:\w+>/clinical/electronic-prescription/descargar-pdf-como-paciente' => '<version>/clinical/electronic-prescription/descargar-pdf-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/electronic-prescription/descargar-pdf-como-paciente' => '<version>/clinical/electronic-prescription/descargar-pdf-como-paciente',
                'GET api/<version:\w+>/clinical/electronic-prescription/verificar-receta' => '<version>/clinical/electronic-prescription/verificar-receta',
                'OPTIONS api/<version:\w+>/clinical/electronic-prescription/verificar-receta' => '<version>/clinical/electronic-prescription/verificar-receta',
                'GET api/<version:\w+>/clinical/electronic-prescription/<id:\d+>' => '<version>/clinical/electronic-prescription/ver',
                'OPTIONS api/<version:\w+>/clinical/electronic-prescription/<id:\d+>' => '<version>/clinical/electronic-prescription/ver',
                'POST api/<version:\w+>/clinical/electronic-prescription/<id:\d+>/emitir' => '<version>/clinical/electronic-prescription/emitir',
                'OPTIONS api/<version:\w+>/clinical/electronic-prescription/<id:\d+>/emitir' => '<version>/clinical/electronic-prescription/emitir',
                'POST api/<version:\w+>/clinical/electronic-prescription/<id:\d+>/anular' => '<version>/clinical/electronic-prescription/anular',
                'OPTIONS api/<version:\w+>/clinical/electronic-prescription/<id:\d+>/anular' => '<version>/clinical/electronic-prescription/anular',
                'GET api/<version:\w+>/clinical/encounter/<encounterId:\d+>/service-requests' => '<version>/clinical/service-request/index',
                'OPTIONS api/<version:\w+>/clinical/encounter/<encounterId:\d+>/service-requests' => '<version>/clinical/service-request/index',
                'POST api/<version:\w+>/clinical/encounter/<encounterId:\d+>/service-requests' => '<version>/clinical/service-request/create',
                'GET api/<version:\w+>/clinical/encounter/<encounterId:\d+>/odontology' => '<version>/clinical/odontology/index',
                'OPTIONS api/<version:\w+>/clinical/encounter/<encounterId:\d+>/odontology' => '<version>/clinical/odontology/index',
                'GET api/<version:\w+>/clinical/encounter/<encounterId:\d+>/ophthalmology' => '<version>/clinical/ophthalmology/index',
                'OPTIONS api/<version:\w+>/clinical/encounter/<encounterId:\d+>/ophthalmology' => '<version>/clinical/ophthalmology/index',
                'GET api/<version:\w+>/clinical/episode-of-care/by-internacion/<internacionId:\d+>' => '<version>/clinical/episode-of-care/by-internacion',
                'OPTIONS api/<version:\w+>/clinical/episode-of-care/by-internacion/<internacionId:\d+>' => '<version>/clinical/episode-of-care/by-internacion',
                'GET api/<version:\w+>/clinical/episode-of-care/<id:\d+>/clinical-bundle' => '<version>/clinical/episode-of-care/clinical-bundle',
                'OPTIONS api/<version:\w+>/clinical/episode-of-care/<id:\d+>/clinical-bundle' => '<version>/clinical/episode-of-care/clinical-bundle',
                'GET api/<version:\w+>/clinical/care-plans/recordatorios-como-paciente' => '<version>/clinical/care-plan/recordatorios-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/care-plans/recordatorios-como-paciente' => '<version>/clinical/care-plan/recordatorios-como-paciente',
                'GET api/<version:\w+>/clinical/care-plans/preferencias-recordatorios-como-paciente' => '<version>/clinical/care-plan/preferencias-recordatorios-como-paciente',
                'PUT api/<version:\w+>/clinical/care-plans/preferencias-recordatorios-como-paciente' => '<version>/clinical/care-plan/actualizar-preferencias-recordatorios-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/care-plans/preferencias-recordatorios-como-paciente' => '<version>/clinical/care-plan/preferencias-recordatorios-como-paciente',
                'GET api/<version:\w+>/clinical/care-plans/active' => '<version>/clinical/care-plan/active',
                'OPTIONS api/<version:\w+>/clinical/care-plans/active' => '<version>/clinical/care-plan/active',
                'GET api/<version:\w+>/clinical/care-plans/<id:\d+>' => '<version>/clinical/care-plan/view',
                'OPTIONS api/<version:\w+>/clinical/care-plans/<id:\d+>' => '<version>/clinical/care-plan/view',
                'POST api/<version:\w+>/clinical/care-plans/<id:\d+>/complete' => '<version>/clinical/care-plan/complete',
                'OPTIONS api/<version:\w+>/clinical/care-plans/<id:\d+>/complete' => '<version>/clinical/care-plan/complete',
                'POST api/<version:\w+>/clinical/care-plans/<id:\d+>/revoke' => '<version>/clinical/care-plan/revoke',
                'OPTIONS api/<version:\w+>/clinical/care-plans/<id:\d+>/revoke' => '<version>/clinical/care-plan/revoke',
                'POST api/<version:\w+>/clinical/care-plans/<id:\d+>/hold' => '<version>/clinical/care-plan/hold',
                'OPTIONS api/<version:\w+>/clinical/care-plans/<id:\d+>/hold' => '<version>/clinical/care-plan/hold',
                'POST api/<version:\w+>/clinical/care-plans/<id:\d+>/activate' => '<version>/clinical/care-plan/activate',
                'OPTIONS api/<version:\w+>/clinical/care-plans/<id:\d+>/activate' => '<version>/clinical/care-plan/activate',
                // Legacy plural (laboratory-results) → canónico singular
                'GET api/<version:\w+>/clinical/laboratory-results/<action:[\w\-]+>' => '<version>/clinical/laboratory-result/<action>',
                'POST api/<version:\w+>/clinical/laboratory-results/<action:[\w\-]+>' => '<version>/clinical/laboratory-result/<action>',
                'OPTIONS api/<version:\w+>/clinical/laboratory-results/<action:[\w\-]+>' => '<version>/clinical/laboratory-result/<action>',
                'GET api/<version:\w+>/clinical/encounter/<encounterId:\d+>/laboratory-results' => '<version>/clinical/laboratory-result/por-encounter',
                'OPTIONS api/<version:\w+>/clinical/encounter/<encounterId:\d+>/laboratory-results' => '<version>/clinical/laboratory-result/por-encounter',
                'GET api/<version:\w+>/clinical/laboratory-result/mis-resultados-como-paciente' => '<version>/clinical/laboratory-result/mis-resultados-como-paciente',
                'POST api/<version:\w+>/clinical/laboratory-result/mis-resultados-como-paciente' => '<version>/clinical/laboratory-result/mis-resultados-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/laboratory-result/mis-resultados-como-paciente' => '<version>/clinical/laboratory-result/mis-resultados-como-paciente',
                'GET api/<version:\w+>/clinical/laboratory-result/ver-informe-como-paciente' => '<version>/clinical/laboratory-result/ver-informe-como-paciente',
                'POST api/<version:\w+>/clinical/laboratory-result/ver-informe-como-paciente' => '<version>/clinical/laboratory-result/ver-informe-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/laboratory-result/ver-informe-como-paciente' => '<version>/clinical/laboratory-result/ver-informe-como-paciente',
                'GET api/<version:\w+>/clinical/laboratory-result/descargar-pdf-como-paciente' => '<version>/clinical/laboratory-result/descargar-pdf-como-paciente',
                'OPTIONS api/<version:\w+>/clinical/laboratory-result/descargar-pdf-como-paciente' => '<version>/clinical/laboratory-result/descargar-pdf-como-paciente',
                'GET api/<version:\w+>/clinical/encounter/<encounterId:\d+>/laboratory-result' => '<version>/clinical/laboratory-result/por-encounter',
                'OPTIONS api/<version:\w+>/clinical/encounter/<encounterId:\d+>/laboratory-result' => '<version>/clinical/laboratory-result/por-encounter',
                // login
                'POST api/<version:\w+>/login' => '<version>/login/login',
                // login biométrico con Didit
                'POST api/<version:\w+>/auth/login-biometrico' => '<version>/auth/login-biometrico',
                'POST api/<version:\w+>/auth/login-revision' => '<version>/auth/login-revision',
                'POST api/<version:\w+>/auth/login-credenciales' => '<version>/auth/login-credenciales',
                'POST api/<version:\w+>/auth/activar-cuenta' => '<version>/auth/activar-cuenta',
                // generar token de prueba para paciente por DNI
                'POST api/<version:\w+>/auth/generar-token-prueba' => '<version>/auth/generar-token-prueba',
                'GET api/<version:\w+>/auth/generar-token-prueba' => '<version>/auth/generar-token-prueba',

                // consulta-chat - chat médico
                'GET api/<version:\w+>/consulta-chat/mensajes/<id:\d+>' => '<version>/consulta-chat/listar-mensajes',
                'OPTIONS api/<version:\w+>/consulta-chat/mensajes/<id:\d+>' => '<version>/consulta-chat/listar-mensajes',
                'POST api/<version:\w+>/consulta-chat/enviar' => '<version>/consulta-chat/enviar',
                'OPTIONS api/<version:\w+>/consulta-chat/enviar' => '<version>/consulta-chat/enviar',
                'POST api/<version:\w+>/consulta-chat/subir' => '<version>/consulta-chat/subir',
                'OPTIONS api/<version:\w+>/consulta-chat/subir' => '<version>/consulta-chat/subir',
                'GET api/<version:\w+>/consulta-chat/estado/<id:\d+>' => '<version>/consulta-chat/estado',
                'OPTIONS api/<version:\w+>/consulta-chat/estado/<id:\d+>' => '<version>/consulta-chat/estado',

                // Media protegida (motivos, chat clínico): Bearer + participantes del encounter
                'GET api/<version:\w+>/media/<scope:[\w\-]+>/<encounterId:\d+>/<filename:[\w\.\-]+>' => '<version>/media/ver',
                'OPTIONS api/<version:\w+>/media/<scope:[\w\-]+>/<encounterId:\d+>/<filename:[\w\.\-]+>' => '<version>/media/options',

                // Motivos de consulta (conversación paciente: texto, audio, fotos)
                'GET api/<version:\w+>/motivos-consulta/mensajes/<id:\d+>' => '<version>/motivos-consulta/listar-mensajes',
                'OPTIONS api/<version:\w+>/motivos-consulta/mensajes/<id:\d+>' => '<version>/motivos-consulta/listar-mensajes',
                'POST api/<version:\w+>/motivos-consulta/enviar' => '<version>/motivos-consulta/enviar',
                'OPTIONS api/<version:\w+>/motivos-consulta/enviar' => '<version>/motivos-consulta/enviar',
                'POST api/<version:\w+>/motivos-consulta/subir' => '<version>/motivos-consulta/subir',
                'OPTIONS api/<version:\w+>/motivos-consulta/subir' => '<version>/motivos-consulta/subir',

                // Care packs (cohorte): asistencia pre-consulta
                'GET api/<version:\w+>/care-packs/assistance' => '<version>/care-packs/assistance',
                'POST api/<version:\w+>/care-packs/assistance' => '<version>/care-packs/assistance',
                'OPTIONS api/<version:\w+>/care-packs/assistance' => '<version>/care-packs/assistance',
                'GET api/<version:\w+>/care-packs/followup' => '<version>/care-packs/followup',
                'POST api/<version:\w+>/care-packs/followup' => '<version>/care-packs/followup',
                'OPTIONS api/<version:\w+>/care-packs/followup' => '<version>/care-packs/followup',

                // Representación paciente (tutela verificada + staff)
                'POST api/<version:\w+>/person-representation/solicitar-menor-como-tutor' => '<version>/person-representation/solicitar-menor-como-tutor',
                'OPTIONS api/<version:\w+>/person-representation/solicitar-menor-como-tutor' => '<version>/person-representation/solicitar-menor-como-tutor',
                'GET api/<version:\w+>/person-representation/mis-vinculos-como-tutor' => '<version>/person-representation/mis-vinculos-como-tutor',
                'POST api/<version:\w+>/person-representation/mis-vinculos-como-tutor' => '<version>/person-representation/mis-vinculos-como-tutor',
                'OPTIONS api/<version:\w+>/person-representation/mis-vinculos-como-tutor' => '<version>/person-representation/mis-vinculos-como-tutor',
                'POST api/<version:\w+>/person-representation/verificar-vinculo-para-staff' => '<version>/person-representation/verificar-vinculo-para-staff',
                'OPTIONS api/<version:\w+>/person-representation/verificar-vinculo-para-staff' => '<version>/person-representation/verificar-vinculo-para-staff',
                'POST api/<version:\w+>/person-representation/bloquear-para-staff' => '<version>/person-representation/bloquear-para-staff',
                'OPTIONS api/<version:\w+>/person-representation/bloquear-para-staff' => '<version>/person-representation/bloquear-para-staff',
                'POST api/<version:\w+>/person-representation/revocar-para-staff' => '<version>/person-representation/revocar-para-staff',
                'OPTIONS api/<version:\w+>/person-representation/revocar-para-staff' => '<version>/person-representation/revocar-para-staff',
                'GET api/<version:\w+>/person-representation/vinculos-paciente-para-staff' => '<version>/person-representation/vinculos-paciente-para-staff',
                'POST api/<version:\w+>/person-representation/vinculos-paciente-para-staff' => '<version>/person-representation/vinculos-paciente-para-staff',
                'OPTIONS api/<version:\w+>/person-representation/vinculos-paciente-para-staff' => '<version>/person-representation/vinculos-paciente-para-staff',
                'GET api/<version:\w+>/person-representation/solicitudes-tutela-pendientes-para-staff' => '<version>/person-representation/solicitudes-tutela-pendientes-para-staff',
                'POST api/<version:\w+>/person-representation/solicitudes-tutela-pendientes-para-staff' => '<version>/person-representation/solicitudes-tutela-pendientes-para-staff',
                'OPTIONS api/<version:\w+>/person-representation/solicitudes-tutela-pendientes-para-staff' => '<version>/person-representation/solicitudes-tutela-pendientes-para-staff',
                'POST api/<version:\w+>/person-representation/designar-representante' => '<version>/person-representation/designar-representante',
                'OPTIONS api/<version:\w+>/person-representation/designar-representante' => '<version>/person-representation/designar-representante',
                'POST api/<version:\w+>/person-representation/revocar-representante' => '<version>/person-representation/revocar-representante',
                'OPTIONS api/<version:\w+>/person-representation/revocar-representante' => '<version>/person-representation/revocar-representante',
                'GET api/<version:\w+>/person-representation/mis-representantes' => '<version>/person-representation/mis-representantes',
                'POST api/<version:\w+>/person-representation/mis-representantes' => '<version>/person-representation/mis-representantes',
                'OPTIONS api/<version:\w+>/person-representation/mis-representantes' => '<version>/person-representation/mis-representantes',
                'GET api/<version:\w+>/person-representation/pacientes-a-cargo' => '<version>/person-representation/pacientes-a-cargo',
                'POST api/<version:\w+>/person-representation/pacientes-a-cargo' => '<version>/person-representation/pacientes-a-cargo',
                'OPTIONS api/<version:\w+>/person-representation/pacientes-a-cargo' => '<version>/person-representation/pacientes-a-cargo',
                'GET api/<version:\w+>/person-representation/preferencias-como-paciente' => '<version>/person-representation/preferencias-como-paciente',
                'POST api/<version:\w+>/person-representation/preferencias-como-paciente' => '<version>/person-representation/preferencias-como-paciente',
                'OPTIONS api/<version:\w+>/person-representation/preferencias-como-paciente' => '<version>/person-representation/preferencias-como-paciente',
                'POST api/<version:\w+>/person-representation/establecer-sujeto-paciente' => '<version>/person-representation/establecer-sujeto-paciente',
                'OPTIONS api/<version:\w+>/person-representation/establecer-sujeto-paciente' => '<version>/person-representation/establecer-sujeto-paciente',

                'GET api/<version:\w+>/paciente-contexto/obtener-como-paciente' => '<version>/paciente-contexto/obtener-como-paciente',
                'POST api/<version:\w+>/paciente-contexto/obtener-como-paciente' => '<version>/paciente-contexto/obtener-como-paciente',
                'OPTIONS api/<version:\w+>/paciente-contexto/obtener-como-paciente' => '<version>/paciente-contexto/obtener-como-paciente',
                'POST api/<version:\w+>/paciente-contexto/actualizar-como-paciente' => '<version>/paciente-contexto/actualizar-como-paciente',
                'OPTIONS api/<version:\w+>/paciente-contexto/actualizar-como-paciente' => '<version>/paciente-contexto/actualizar-como-paciente',
                'GET api/<version:\w+>/paciente-contexto/sugerir-provincias-como-paciente' => '<version>/paciente-contexto/sugerir-provincias-como-paciente',
                'POST api/<version:\w+>/paciente-contexto/sugerir-provincias-como-paciente' => '<version>/paciente-contexto/sugerir-provincias-como-paciente',
                'OPTIONS api/<version:\w+>/paciente-contexto/sugerir-provincias-como-paciente' => '<version>/paciente-contexto/sugerir-provincias-como-paciente',
                'GET api/<version:\w+>/paciente-contexto/buscar-recurso-provincial-como-paciente' => '<version>/paciente-contexto/buscar-recurso-provincial-como-paciente',
                'POST api/<version:\w+>/paciente-contexto/buscar-recurso-provincial-como-paciente' => '<version>/paciente-contexto/buscar-recurso-provincial-como-paciente',
                'OPTIONS api/<version:\w+>/paciente-contexto/buscar-recurso-provincial-como-paciente' => '<version>/paciente-contexto/buscar-recurso-provincial-como-paciente',
                
                // Turnos / agenda profesional API: día operativo; ABM profesional_efector_servicio_agenda = listar|crear|actualizar|eliminar (propio) vs *-para-recurso (staff; query id_efector + id_profesional_efector_servicio)
                'GET api/<version:\w+>/profesional-agenda/dia' => '<version>/profesional-agenda/dia',
                'OPTIONS api/<version:\w+>/profesional-agenda/dia' => '<version>/profesional-agenda/dia',
                'GET api/<version:\w+>/profesional-agenda/listar-para-recurso' => '<version>/profesional-agenda/listar-para-recurso',
                'OPTIONS api/<version:\w+>/profesional-agenda/listar-para-recurso' => '<version>/profesional-agenda/listar-para-recurso',
                'GET api/<version:\w+>/profesional-agenda/listar' => '<version>/profesional-agenda/listar',
                'OPTIONS api/<version:\w+>/profesional-agenda/listar' => '<version>/profesional-agenda/listar',
                'POST api/<version:\w+>/profesional-agenda/crear-para-recurso' => '<version>/profesional-agenda/crear-para-recurso',
                'OPTIONS api/<version:\w+>/profesional-agenda/crear-para-recurso' => '<version>/profesional-agenda/crear-para-recurso',
                'POST api/<version:\w+>/profesional-agenda/crear' => '<version>/profesional-agenda/crear',
                'OPTIONS api/<version:\w+>/profesional-agenda/crear' => '<version>/profesional-agenda/crear',
                'PUT api/<version:\w+>/profesional-agenda/actualizar-para-recurso/<id:\d+>' => '<version>/profesional-agenda/actualizar-para-recurso',
                'PATCH api/<version:\w+>/profesional-agenda/actualizar-para-recurso/<id:\d+>' => '<version>/profesional-agenda/actualizar-para-recurso',
                'OPTIONS api/<version:\w+>/profesional-agenda/actualizar-para-recurso/<id:\d+>' => '<version>/profesional-agenda/actualizar-para-recurso',
                'PUT api/<version:\w+>/profesional-agenda/actualizar/<id:\d+>' => '<version>/profesional-agenda/actualizar',
                'PATCH api/<version:\w+>/profesional-agenda/actualizar/<id:\d+>' => '<version>/profesional-agenda/actualizar',
                'OPTIONS api/<version:\w+>/profesional-agenda/actualizar/<id:\d+>' => '<version>/profesional-agenda/actualizar',
                'DELETE api/<version:\w+>/profesional-agenda/eliminar-para-recurso/<id:\d+>' => '<version>/profesional-agenda/eliminar-para-recurso',
                'OPTIONS api/<version:\w+>/profesional-agenda/eliminar-para-recurso/<id:\d+>' => '<version>/profesional-agenda/eliminar-para-recurso',
                'DELETE api/<version:\w+>/profesional-agenda/eliminar/<id:\d+>' => '<version>/profesional-agenda/eliminar',
                'OPTIONS api/<version:\w+>/profesional-agenda/eliminar/<id:\d+>' => '<version>/profesional-agenda/eliminar',
                'GET api/<version:\w+>/profesional-agenda/configurar-agenda' => '<version>/profesional-agenda/configurar-agenda',
                'POST api/<version:\w+>/profesional-agenda/configurar-agenda' => '<version>/profesional-agenda/configurar-agenda',
                'OPTIONS api/<version:\w+>/profesional-agenda/configurar-agenda' => '<version>/profesional-agenda/configurar-agenda',
                'POST api/<version:\w+>/profesional-agenda/preview-configurar-agenda' => '<version>/profesional-agenda/preview-configurar-agenda',
                'OPTIONS api/<version:\w+>/profesional-agenda/preview-configurar-agenda' => '<version>/profesional-agenda/preview-configurar-agenda',
                'GET api/<version:\w+>/profesional-agenda/preview-impacto-agenda' => '<version>/profesional-agenda/preview-impacto-agenda',
                'POST api/<version:\w+>/profesional-agenda/preview-impacto-agenda' => '<version>/profesional-agenda/preview-impacto-agenda',
                'OPTIONS api/<version:\w+>/profesional-agenda/preview-impacto-agenda' => '<version>/profesional-agenda/preview-impacto-agenda',
                'GET api/<version:\w+>/profesional-efector-servicio/crear-flow' => '<version>/profesional-efector-servicio/crear-flow',
                'POST api/<version:\w+>/profesional-efector-servicio/crear-flow' => '<version>/profesional-efector-servicio/crear-flow',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/crear-flow' => '<version>/profesional-efector-servicio/crear-flow',
                'GET api/<version:\w+>/profesional-efector-servicio/cargar-cuil-profesional' => '<version>/profesional-efector-servicio/cargar-cuil-profesional',
                'POST api/<version:\w+>/profesional-efector-servicio/cargar-cuil-profesional' => '<version>/profesional-efector-servicio/cargar-cuil-profesional',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/cargar-cuil-profesional' => '<version>/profesional-efector-servicio/cargar-cuil-profesional',
                'GET api/<version:\w+>/profesional-efector-servicio/listar-codigos-servicio-fhir' => '<version>/profesional-efector-servicio/listar-codigos-servicio-fhir',
                'POST api/<version:\w+>/profesional-efector-servicio/listar-codigos-servicio-fhir' => '<version>/profesional-efector-servicio/listar-codigos-servicio-fhir',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/listar-codigos-servicio-fhir' => '<version>/profesional-efector-servicio/listar-codigos-servicio-fhir',
                'GET api/<version:\w+>/profesional-efector-servicio/guardar-codigo-servicio-fhir' => '<version>/profesional-efector-servicio/guardar-codigo-servicio-fhir',
                'POST api/<version:\w+>/profesional-efector-servicio/guardar-codigo-servicio-fhir' => '<version>/profesional-efector-servicio/guardar-codigo-servicio-fhir',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/guardar-codigo-servicio-fhir' => '<version>/profesional-efector-servicio/guardar-codigo-servicio-fhir',
                'GET api/<version:\w+>/profesional-efector-servicio/listar-schedules-hapi' => '<version>/profesional-efector-servicio/listar-schedules-hapi',
                'POST api/<version:\w+>/profesional-efector-servicio/listar-schedules-hapi' => '<version>/profesional-efector-servicio/listar-schedules-hapi',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/listar-schedules-hapi' => '<version>/profesional-efector-servicio/listar-schedules-hapi',
                'GET api/<version:\w+>/profesional-efector-servicio/preview-vinculo-schedule-hapi' => '<version>/profesional-efector-servicio/preview-vinculo-schedule-hapi',
                'POST api/<version:\w+>/profesional-efector-servicio/preview-vinculo-schedule-hapi' => '<version>/profesional-efector-servicio/preview-vinculo-schedule-hapi',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/preview-vinculo-schedule-hapi' => '<version>/profesional-efector-servicio/preview-vinculo-schedule-hapi',
                'GET api/<version:\w+>/profesional-efector-servicio/confirmar-vinculo-schedule-hapi' => '<version>/profesional-efector-servicio/confirmar-vinculo-schedule-hapi',
                'POST api/<version:\w+>/profesional-efector-servicio/confirmar-vinculo-schedule-hapi' => '<version>/profesional-efector-servicio/confirmar-vinculo-schedule-hapi',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/confirmar-vinculo-schedule-hapi' => '<version>/profesional-efector-servicio/confirmar-vinculo-schedule-hapi',
                'GET api/<version:\w+>/profesional-agenda/elegir-conflicto-agenda' => '<version>/profesional-agenda/elegir-conflicto-agenda',
                'POST api/<version:\w+>/profesional-agenda/elegir-conflicto-agenda' => '<version>/profesional-agenda/elegir-conflicto-agenda',
                'OPTIONS api/<version:\w+>/profesional-agenda/elegir-conflicto-agenda' => '<version>/profesional-agenda/elegir-conflicto-agenda',
                'GET api/<version:\w+>/profesional-agenda/elegir-resolucion-conflicto-agenda-para-paciente' => '<version>/profesional-agenda/elegir-resolucion-conflicto-agenda-para-paciente',
                'POST api/<version:\w+>/profesional-agenda/elegir-resolucion-conflicto-agenda-para-paciente' => '<version>/profesional-agenda/elegir-resolucion-conflicto-agenda-para-paciente',
                'OPTIONS api/<version:\w+>/profesional-agenda/elegir-resolucion-conflicto-agenda-para-paciente' => '<version>/profesional-agenda/elegir-resolucion-conflicto-agenda-para-paciente',
                'POST api/<version:\w+>/profesional-agenda/resolver-conflictos-flow' => '<version>/profesional-agenda/resolver-conflictos-flow',
                'OPTIONS api/<version:\w+>/profesional-agenda/resolver-conflictos-flow' => '<version>/profesional-agenda/resolver-conflictos-flow',
                'GET api/<version:\w+>/profesional-agenda/ver-agenda-dia' => '<version>/profesional-agenda/ver-agenda-dia',
                'POST api/<version:\w+>/profesional-agenda/ver-agenda-dia' => '<version>/profesional-agenda/ver-agenda-dia',
                'OPTIONS api/<version:\w+>/profesional-agenda/ver-agenda-dia' => '<version>/profesional-agenda/ver-agenda-dia',

                // Cobertura EMER/IMP (roster entrada/salida); no cupos paciente
                'GET api/<version:\w+>/profesional-cobertura/gestionar' => '<version>/profesional-cobertura/gestionar',
                'POST api/<version:\w+>/profesional-cobertura/gestionar' => '<version>/profesional-cobertura/gestionar',
                'OPTIONS api/<version:\w+>/profesional-cobertura/gestionar' => '<version>/profesional-cobertura/gestionar',
                'GET api/<version:\w+>/profesional-cobertura/listar' => '<version>/profesional-cobertura/listar',
                'OPTIONS api/<version:\w+>/profesional-cobertura/listar' => '<version>/profesional-cobertura/listar',
                'GET api/<version:\w+>/profesional-cobertura/listar-para-recurso' => '<version>/profesional-cobertura/listar-para-recurso',
                'OPTIONS api/<version:\w+>/profesional-cobertura/listar-para-recurso' => '<version>/profesional-cobertura/listar-para-recurso',
                'POST api/<version:\w+>/profesional-cobertura/crear' => '<version>/profesional-cobertura/crear',
                'OPTIONS api/<version:\w+>/profesional-cobertura/crear' => '<version>/profesional-cobertura/crear',
                'POST api/<version:\w+>/profesional-cobertura/crear-para-recurso' => '<version>/profesional-cobertura/crear-para-recurso',
                'OPTIONS api/<version:\w+>/profesional-cobertura/crear-para-recurso' => '<version>/profesional-cobertura/crear-para-recurso',
                'PUT api/<version:\w+>/profesional-cobertura/actualizar-para-recurso/<id:\d+>' => '<version>/profesional-cobertura/actualizar-para-recurso',
                'PATCH api/<version:\w+>/profesional-cobertura/actualizar-para-recurso/<id:\d+>' => '<version>/profesional-cobertura/actualizar-para-recurso',
                'OPTIONS api/<version:\w+>/profesional-cobertura/actualizar-para-recurso/<id:\d+>' => '<version>/profesional-cobertura/actualizar-para-recurso',
                'PUT api/<version:\w+>/profesional-cobertura/actualizar/<id:\d+>' => '<version>/profesional-cobertura/actualizar',
                'PATCH api/<version:\w+>/profesional-cobertura/actualizar/<id:\d+>' => '<version>/profesional-cobertura/actualizar',
                'OPTIONS api/<version:\w+>/profesional-cobertura/actualizar/<id:\d+>' => '<version>/profesional-cobertura/actualizar',
                'DELETE api/<version:\w+>/profesional-cobertura/eliminar-para-recurso/<id:\d+>' => '<version>/profesional-cobertura/eliminar-para-recurso',
                'OPTIONS api/<version:\w+>/profesional-cobertura/eliminar-para-recurso/<id:\d+>' => '<version>/profesional-cobertura/eliminar-para-recurso',
                'DELETE api/<version:\w+>/profesional-cobertura/eliminar/<id:\d+>' => '<version>/profesional-cobertura/eliminar',
                'OPTIONS api/<version:\w+>/profesional-cobertura/eliminar/<id:\d+>' => '<version>/profesional-cobertura/eliminar',

                'GET api/<version:\w+>/profesional-efector-servicio/editar-condicion-laboral' => '<version>/profesional-efector-servicio/editar-condicion-laboral',
                'POST api/<version:\w+>/profesional-efector-servicio/editar-condicion-laboral' => '<version>/profesional-efector-servicio/editar-condicion-laboral',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/editar-condicion-laboral' => '<version>/profesional-efector-servicio/editar-condicion-laboral',
                'GET api/<version:\w+>/profesional-efector-servicio/crear-condicion-laboral' => '<version>/profesional-efector-servicio/crear-condicion-laboral',
                'POST api/<version:\w+>/profesional-efector-servicio/crear-condicion-laboral' => '<version>/profesional-efector-servicio/crear-condicion-laboral',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/crear-condicion-laboral' => '<version>/profesional-efector-servicio/crear-condicion-laboral',
                'GET api/<version:\w+>/profesional-efector-servicio/cargar-licencia-como-profesional' => '<version>/profesional-efector-servicio/cargar-licencia-como-profesional',
                'POST api/<version:\w+>/profesional-efector-servicio/cargar-licencia-como-profesional' => '<version>/profesional-efector-servicio/cargar-licencia-como-profesional',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/cargar-licencia-como-profesional' => '<version>/profesional-efector-servicio/cargar-licencia-como-profesional',
                'GET api/<version:\w+>/profesional-efector-servicio/cargar-licencia-para-profesional' => '<version>/profesional-efector-servicio/cargar-licencia-para-profesional',
                'POST api/<version:\w+>/profesional-efector-servicio/cargar-licencia-para-profesional' => '<version>/profesional-efector-servicio/cargar-licencia-para-profesional',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/cargar-licencia-para-profesional' => '<version>/profesional-efector-servicio/cargar-licencia-para-profesional',
                'GET api/<version:\w+>/profesional-efector-servicio/cargar-licencia-como-profesional-flow' => '<version>/profesional-efector-servicio/cargar-licencia-como-profesional-flow',
                'POST api/<version:\w+>/profesional-efector-servicio/cargar-licencia-como-profesional-flow' => '<version>/profesional-efector-servicio/cargar-licencia-como-profesional-flow',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/cargar-licencia-como-profesional-flow' => '<version>/profesional-efector-servicio/cargar-licencia-como-profesional-flow',
                'GET api/<version:\w+>/profesional-efector-servicio/cargar-licencia-para-profesional-flow' => '<version>/profesional-efector-servicio/cargar-licencia-para-profesional-flow',
                'POST api/<version:\w+>/profesional-efector-servicio/cargar-licencia-para-profesional-flow' => '<version>/profesional-efector-servicio/cargar-licencia-para-profesional-flow',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/cargar-licencia-para-profesional-flow' => '<version>/profesional-efector-servicio/cargar-licencia-para-profesional-flow',
                'POST api/<version:\w+>/profesional-efector-servicio/preview-impacto-licencia' => '<version>/profesional-efector-servicio/preview-impacto-licencia',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/preview-impacto-licencia' => '<version>/profesional-efector-servicio/preview-impacto-licencia',
                
                // Turnos (rutas de compat / consumo histórico): algunos clientes consumen /api/<v>/turnos/*
                // Nota: los descriptores JSON viven en `modules/api/v1/views/json/...` pero se exponen como `/api/<v>/turnos/*`.
                'GET api/<version:\w+>/turnos/listar-como-paciente' => '<version>/turnos/listar-como-paciente',
                'POST api/<version:\w+>/turnos/listar-como-paciente' => '<version>/turnos/listar-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/listar-como-paciente' => '<version>/turnos/listar-como-paciente',
                'GET api/<version:\w+>/turnos/slots-disponibles-como-paciente' => '<version>/turnos/slots-disponibles-como-paciente',
                'POST api/<version:\w+>/turnos/slots-disponibles-como-paciente' => '<version>/turnos/slots-disponibles-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/slots-disponibles-como-paciente' => '<version>/turnos/slots-disponibles-como-paciente',
                'GET api/<version:\w+>/turnos/slots-dias-disponibles-como-paciente' => '<version>/turnos/slots-dias-disponibles-como-paciente',
                'POST api/<version:\w+>/turnos/slots-dias-disponibles-como-paciente' => '<version>/turnos/slots-dias-disponibles-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/slots-dias-disponibles-como-paciente' => '<version>/turnos/slots-dias-disponibles-como-paciente',
                'GET api/<version:\w+>/turnos/reserva-triage-catalogo' => '<version>/turnos/reserva-triage-catalogo',
                'OPTIONS api/<version:\w+>/turnos/reserva-triage-catalogo' => '<version>/turnos/reserva-triage-catalogo',
                'GET api/<version:\w+>/turnos/reserva-triage-paso' => '<version>/turnos/reserva-triage-paso',
                'POST api/<version:\w+>/turnos/reserva-triage-paso' => '<version>/turnos/reserva-triage-paso',
                'OPTIONS api/<version:\w+>/turnos/reserva-triage-paso' => '<version>/turnos/reserva-triage-paso',
                'GET api/<version:\w+>/turnos/reserva-triage-urgencia' => '<version>/turnos/reserva-triage-urgencia',
                'POST api/<version:\w+>/turnos/reserva-triage-urgencia' => '<version>/turnos/reserva-triage-urgencia',
                'OPTIONS api/<version:\w+>/turnos/reserva-triage-urgencia' => '<version>/turnos/reserva-triage-urgencia',
                'GET api/<version:\w+>/consultas-seguimiento/paso' => '<version>/consultas-seguimiento/paso',
                'POST api/<version:\w+>/consultas-seguimiento/paso' => '<version>/consultas-seguimiento/paso',
                'OPTIONS api/<version:\w+>/consultas-seguimiento/paso' => '<version>/consultas-seguimiento/paso',
                'GET api/<version:\w+>/encounter-journey/estado' => '<version>/encounter-journey/estado',
                'POST api/<version:\w+>/encounter-journey/estado' => '<version>/encounter-journey/estado',
                'OPTIONS api/<version:\w+>/encounter-journey/estado' => '<version>/encounter-journey/estado',
                'GET api/<version:\w+>/encounter-journey/motivos-intake' => '<version>/encounter-journey/motivos-intake',
                'POST api/<version:\w+>/encounter-journey/motivos-intake' => '<version>/encounter-journey/motivos-intake',
                'OPTIONS api/<version:\w+>/encounter-journey/motivos-intake' => '<version>/encounter-journey/motivos-intake',
                'GET api/<version:\w+>/turnos/elegir-pendiente-como-paciente' => '<version>/turnos/elegir-pendiente-como-paciente',
                'POST api/<version:\w+>/turnos/elegir-pendiente-como-paciente' => '<version>/turnos/elegir-pendiente-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/elegir-pendiente-como-paciente' => '<version>/turnos/elegir-pendiente-como-paciente',
                'GET api/<version:\w+>/turnos/elegir-motivo-cancelacion-como-paciente' => '<version>/turnos/elegir-motivo-cancelacion-como-paciente',
                'POST api/<version:\w+>/turnos/elegir-motivo-cancelacion-como-paciente' => '<version>/turnos/elegir-motivo-cancelacion-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/elegir-motivo-cancelacion-como-paciente' => '<version>/turnos/elegir-motivo-cancelacion-como-paciente',
                'GET api/<version:\w+>/turnos/slots-reprogramar-como-paciente' => '<version>/turnos/slots-reprogramar-como-paciente',
                'POST api/<version:\w+>/turnos/slots-reprogramar-como-paciente' => '<version>/turnos/slots-reprogramar-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/slots-reprogramar-como-paciente' => '<version>/turnos/slots-reprogramar-como-paciente',
                'GET api/<version:\w+>/turnos/elegir-conflicto-agenda-como-paciente' => '<version>/turnos/elegir-conflicto-agenda-como-paciente',
                'POST api/<version:\w+>/turnos/elegir-conflicto-agenda-como-paciente' => '<version>/turnos/elegir-conflicto-agenda-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/elegir-conflicto-agenda-como-paciente' => '<version>/turnos/elegir-conflicto-agenda-como-paciente',
                'GET api/<version:\w+>/turnos/elegir-resolucion-conflicto-agenda-como-paciente' => '<version>/turnos/elegir-resolucion-conflicto-agenda-como-paciente',
                'POST api/<version:\w+>/turnos/elegir-resolucion-conflicto-agenda-como-paciente' => '<version>/turnos/elegir-resolucion-conflicto-agenda-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/elegir-resolucion-conflicto-agenda-como-paciente' => '<version>/turnos/elegir-resolucion-conflicto-agenda-como-paciente',
                'POST api/<version:\w+>/turnos/resolver-conflicto-agenda-como-paciente' => '<version>/turnos/resolver-conflicto-agenda-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/resolver-conflicto-agenda-como-paciente' => '<version>/turnos/resolver-conflicto-agenda-como-paciente',
                'GET api/<version:\w+>/turnos/elegir-en-resolucion-como-paciente' => '<version>/turnos/elegir-en-resolucion-como-paciente',
                'POST api/<version:\w+>/turnos/elegir-en-resolucion-como-paciente' => '<version>/turnos/elegir-en-resolucion-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/elegir-en-resolucion-como-paciente' => '<version>/turnos/elegir-en-resolucion-como-paciente',
                'GET api/<version:\w+>/turnos/slots-reubicar-como-paciente' => '<version>/turnos/slots-reubicar-como-paciente',
                'POST api/<version:\w+>/turnos/slots-reubicar-como-paciente' => '<version>/turnos/slots-reubicar-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/slots-reubicar-como-paciente' => '<version>/turnos/slots-reubicar-como-paciente',
                'POST api/<version:\w+>/turnos/reubicar-como-paciente' => '<version>/turnos/reubicar-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/reubicar-como-paciente' => '<version>/turnos/reubicar-como-paciente',
                'POST api/<version:\w+>/turnos/lista-espera-inscribir-como-paciente' => '<version>/turnos/lista-espera-inscribir-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/lista-espera-inscribir-como-paciente' => '<version>/turnos/lista-espera-inscribir-como-paciente',
                'POST api/<version:\w+>/turnos/lista-espera-cancelar-como-paciente' => '<version>/turnos/lista-espera-cancelar-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/lista-espera-cancelar-como-paciente' => '<version>/turnos/lista-espera-cancelar-como-paciente',
                'GET api/<version:\w+>/turnos/lista-espera-estado-como-paciente' => '<version>/turnos/lista-espera-estado-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/lista-espera-estado-como-paciente' => '<version>/turnos/lista-espera-estado-como-paciente',
                'POST api/<version:\w+>/turnos/lista-espera-aceptar-oferta-como-paciente' => '<version>/turnos/lista-espera-aceptar-oferta-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/lista-espera-aceptar-oferta-como-paciente' => '<version>/turnos/lista-espera-aceptar-oferta-como-paciente',
                'POST api/<version:\w+>/turnos/elegir-shortlist-resolucion-como-paciente' => '<version>/turnos/elegir-shortlist-resolucion-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/elegir-shortlist-resolucion-como-paciente' => '<version>/turnos/elegir-shortlist-resolucion-como-paciente',
                'GET api/<version:\w+>/turnos/preferencias-agenda-como-paciente' => '<version>/turnos/preferencias-agenda-como-paciente',
                'POST api/<version:\w+>/turnos/preferencias-agenda-como-paciente' => '<version>/turnos/preferencias-agenda-como-paciente',
                'OPTIONS api/<version:\w+>/turnos/preferencias-agenda-como-paciente' => '<version>/turnos/preferencias-agenda-como-paciente',
                'GET api/<version:\w+>/turnos/calendario-ocupacion-dia' => '<version>/turnos/calendario-ocupacion-dia',
                'POST api/<version:\w+>/turnos/calendario-ocupacion-dia' => '<version>/turnos/calendario-ocupacion-dia',
                'OPTIONS api/<version:\w+>/turnos/calendario-ocupacion-dia' => '<version>/turnos/calendario-ocupacion-dia',
                'GET api/<version:\w+>/turnos/eventos' => '<version>/turnos/consultar-ocupacion-dia',
                'POST api/<version:\w+>/turnos/eventos' => '<version>/turnos/consultar-ocupacion-dia',
                'OPTIONS api/<version:\w+>/turnos/eventos' => '<version>/turnos/consultar-ocupacion-dia',
                'GET api/<version:\w+>/turnos/indicadores-agenda' => '<version>/turnos/indicadores-agenda',
                'POST api/<version:\w+>/turnos/indicadores-agenda' => '<version>/turnos/indicadores-agenda',
                'OPTIONS api/<version:\w+>/turnos/indicadores-agenda' => '<version>/turnos/indicadores-agenda',
                'GET api/<version:\w+>/turnos/proximo-disponible' => '<version>/turnos/consultar-proximo-disponible',
                'POST api/<version:\w+>/turnos/proximo-disponible' => '<version>/turnos/consultar-proximo-disponible',
                'OPTIONS api/<version:\w+>/turnos/proximo-disponible' => '<version>/turnos/consultar-proximo-disponible',
                'POST api/<version:\w+>/devices/push-token' => '<version>/device/push-token',
                'OPTIONS api/<version:\w+>/devices/push-token' => '<version>/device/push-token',
                'POST api/<version:\w+>/client-diagnostic/registrar' => '<version>/client-diagnostic/registrar',
                'OPTIONS api/<version:\w+>/client-diagnostic/registrar' => '<version>/client-diagnostic/registrar',
                'GET api/<version:\w+>/notificaciones/listar' => '<version>/notificaciones/listar',
                'POST api/<version:\w+>/notificaciones/listar' => '<version>/notificaciones/listar',
                'OPTIONS api/<version:\w+>/notificaciones/listar' => '<version>/notificaciones/listar',
                'POST api/<version:\w+>/notificaciones/marcar-leida' => '<version>/notificaciones/marcar-leida',
                'OPTIONS api/<version:\w+>/notificaciones/marcar-leida' => '<version>/notificaciones/marcar-leida',
                'GET api/<version:\w+>/solicitud-profesional' => '<version>/solicitud-profesional/listar',
                'OPTIONS api/<version:\w+>/solicitud-profesional' => '<version>/solicitud-profesional/listar',
                'POST api/<version:\w+>/solicitud-profesional' => '<version>/solicitud-profesional/crear',
                
                // Personas Timeline API (historia clínica)
                'GET api/<version:\w+>/personas/<id:\d+>/signos-vitales' => '<version>/persona/signos-vitales',
                'OPTIONS api/<version:\w+>/personas/<id:\d+>/signos-vitales' => '<version>/persona/signos-vitales',
                'GET api/<version:\w+>/personas/<id:\d+>/historia-clinica' => '<version>/pacientes/historia-clinica',
                'OPTIONS api/<version:\w+>/personas/<id:\d+>/historia-clinica' => '<version>/pacientes/historia-clinica',

                // Config API
                // (Se eliminan endpoints de listados en ConfigController; ver Efectores/PES/Catálogos/SesiónOperativa)
                
                // Efectores API - Búsqueda
                'GET api/<version:\w+>/efectores/buscar' => '<version>/efectores/buscar',
                'POST api/<version:\w+>/efectores/buscar' => '<version>/efectores/buscar',
                'OPTIONS api/<version:\w+>/efectores/buscar' => '<version>/efectores/buscar',
                'GET api/<version:\w+>/efectores/listar-servicios-habilitados' => '<version>/efectores/listar-servicios-habilitados',
                'POST api/<version:\w+>/efectores/listar-servicios-habilitados' => '<version>/efectores/listar-servicios-habilitados',
                'OPTIONS api/<version:\w+>/efectores/listar-servicios-habilitados' => '<version>/efectores/listar-servicios-habilitados',

                // Profesional efector servicio (PES) API - Búsqueda / listados UI
                'GET api/<version:\w+>/profesional-efector-servicio/autocomplete' => '<version>/profesional-efector-servicio/autocomplete',
                'POST api/<version:\w+>/profesional-efector-servicio/autocomplete' => '<version>/profesional-efector-servicio/autocomplete',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/autocomplete' => '<version>/profesional-efector-servicio/autocomplete',
                'GET api/<version:\w+>/profesional-efector-servicio/listar-mis-servicios-en-efector' => '<version>/profesional-efector-servicio/listar-mis-servicios-en-efector',
                'POST api/<version:\w+>/profesional-efector-servicio/listar-mis-servicios-en-efector' => '<version>/profesional-efector-servicio/listar-mis-servicios-en-efector',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/listar-mis-servicios-en-efector' => '<version>/profesional-efector-servicio/listar-mis-servicios-en-efector',
                'GET api/<version:\w+>/profesional-efector-servicio/listar-por-efector' => '<version>/profesional-efector-servicio/listar-por-efector',
                'POST api/<version:\w+>/profesional-efector-servicio/listar-por-efector' => '<version>/profesional-efector-servicio/listar-por-efector',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/listar-por-efector' => '<version>/profesional-efector-servicio/listar-por-efector',
                'GET api/<version:\w+>/info' => '<version>/info/index',
                'POST api/<version:\w+>/info' => '<version>/info/index',
                'OPTIONS api/<version:\w+>/info' => '<version>/info/index',
                'GET api/<version:\w+>/listar' => '<version>/listar/index',
                'POST api/<version:\w+>/listar' => '<version>/listar/index',
                'OPTIONS api/<version:\w+>/listar' => '<version>/listar/index',
                'GET api/<version:\w+>/editar' => '<version>/editar/index',
                'POST api/<version:\w+>/editar' => '<version>/editar/index',
                'OPTIONS api/<version:\w+>/editar' => '<version>/editar/index',
                'GET api/<version:\w+>/profesional-efector-servicio/condiciones-laborales-catalogo' => '<version>/profesional-efector-servicio/condiciones-laborales-catalogo',
                'OPTIONS api/<version:\w+>/profesional-efector-servicio/condiciones-laborales-catalogo' => '<version>/profesional-efector-servicio/condiciones-laborales-catalogo',

                // Catálogos API
                'GET api/<version:\w+>/catalogos/encounter-classes' => '<version>/catalogos/encounter-classes',
                'OPTIONS api/<version:\w+>/catalogos/encounter-classes' => '<version>/catalogos/encounter-classes',
                'POST api/<version:\w+>/catalogos/departamentos-depdrop' => '<version>/catalogos/departamentos-depdrop',
                'POST api/<version:\w+>/catalogos/localidades-depdrop' => '<version>/catalogos/localidades-depdrop',
                'POST api/<version:\w+>/catalogos/barrios-depdrop' => '<version>/catalogos/barrios-depdrop',
                'POST api/<version:\w+>/catalogos/especialidades-depdrop' => '<version>/catalogos/especialidades-depdrop',
                'POST api/<version:\w+>/catalogos/salas-por-piso-depdrop' => '<version>/catalogos/salas-por-piso-depdrop',

                // Sesión Operativa API
                'POST api/<version:\w+>/sesion-operativa/establecer' => '<version>/sesion-operativa/establecer',
                'OPTIONS api/<version:\w+>/sesion-operativa/establecer' => '<version>/sesion-operativa/establecer',

                // Acciones comunes (web SPA / móvil; filtrado por permisos en servicio)
                'GET api/<version:\w+>/acciones/comunes' => '<version>/acciones/comunes',
                'OPTIONS api/<version:\w+>/acciones/comunes' => '<version>/acciones/comunes',
                
                // Descriptores JSON (plantillas en `frontend/modules/api/v1/views/json/{entidad}/{accion}.json`)
                // se exponen como endpoints normales: `/api/v1/<entidad>/<accion>`.
                //
                // Importante: las reglas explícitas de API (arriba) tienen prioridad; esta regla “catch-all”
                // solo aplica a rutas no declaradas explícitamente.
                'GET api/<version:\w+>/<controller:[\\w-]+>/<action:[\\w-]+>' => '<version>/<controller>/<action>',
                'POST api/<version:\w+>/<controller:[\\w-]+>/<action:[\\w-]+>' => '<version>/<controller>/<action>',
                
                // Audio API (Speech-to-Text)
                'GET api/<version:\w+>/audio/stt-config' => '<version>/audio/stt-config',
                'OPTIONS api/<version:\w+>/audio/stt-config' => '<version>/audio/stt-config',
                'POST api/<version:\w+>/audio/transcribir' => '<version>/audio/transcribir',
                'OPTIONS api/<version:\w+>/audio/transcribir' => '<version>/audio/transcribir',

                // Panel de inicio (web site/index + móvil staff)
                'GET api/<version:\w+>/home/panel' => '<version>/home/panel',
                'OPTIONS api/<version:\w+>/home/panel' => '<version>/home/panel',

                // Quirófano — agenda (salas + cirugías)
                'GET api/<version:\w+>/quirofano/salas' => '<version>/quirofano/listar-salas',
                'POST api/<version:\w+>/quirofano/salas' => '<version>/quirofano/listar-salas',
                'OPTIONS api/<version:\w+>/quirofano/salas' => '<version>/quirofano/options',
                'GET api/<version:\w+>/quirofano/salas/<id:\d+>' => '<version>/quirofano/ver-sala',
                'PATCH api/<version:\w+>/quirofano/salas/<id:\d+>' => '<version>/quirofano/actualizar-sala',
                'DELETE api/<version:\w+>/quirofano/salas/<id:\d+>' => '<version>/quirofano/eliminar-sala',
                'OPTIONS api/<version:\w+>/quirofano/salas/<id:\d+>' => '<version>/quirofano/options',
                'GET api/<version:\w+>/quirofano/cirugias' => '<version>/quirofano/listar-cirugias',
                'POST api/<version:\w+>/quirofano/cirugias' => '<version>/quirofano/listar-cirugias',
                'OPTIONS api/<version:\w+>/quirofano/cirugias' => '<version>/quirofano/options',
                'GET api/<version:\w+>/quirofano/cirugias/<id:\d+>' => '<version>/quirofano/ver-cirugia',
                'PATCH api/<version:\w+>/quirofano/cirugias/<id:\d+>' => '<version>/quirofano/actualizar-cirugia',
                'PATCH api/<version:\w+>/quirofano/cirugias/<id:\d+>/estado' => '<version>/quirofano/estado-cirugia',
                'OPTIONS api/<version:\w+>/quirofano/cirugias/<id:\d+>' => '<version>/quirofano/options',
                'OPTIONS api/<version:\w+>/quirofano/cirugias/<id:\d+>/estado' => '<version>/quirofano/options',
            ],            
        ],
    ],
    'params' => $params,
    'modules' => [
        'user-management' => [
            'class' => \common\modules\UserManagementCompatModule::class,
            'controllerMap' => [
                'auth' => 'frontend\controllers\userManagement\AuthController',
                'permission' => 'admin\controllers\LegacyRbacRedirectController',
                'role' => 'admin\controllers\LegacyRbacRedirectController',
                'auth-item-group' => 'admin\controllers\LegacyRbacRedirectController',
                'user' => 'admin\controllers\UserAccountController',
                'user-permission' => 'admin\controllers\UserRoleController',
            ],
            //'registrationFormClass' => 'common\models\User',
            // 'enableRegistration' => true,
            // Here you can set your handler to change layout for any controller or action
            // Tip: you can use this event in any module
            'on beforeAction' => function (yii\base\ActionEvent $event) {
                if ($event->action->uniqueId === 'auth/login') {
                    $event->action->controller->layout = '@frontend/views/layouts/loginLayout.php';
                }
            },
        ],
        'gridview' => [
            'class' => 'kartik\grid\Module',
        ],
        'v1' => [
            'class' => 'frontend\modules\api\v1\Module',
            'basePath' => '@frontend/modules/api/v1',
            'controllerNamespace' => 'frontend\modules\api\v1\controllers',
            'controllerMap' => [
                'servicio-teleconsulta' => \frontend\modules\api\v1\controllers\ServicioTeleconsultaPoliticaController::class,
            ],
        ],           
    ],
    'aliases' => [
        '@kartik/switchinput' => '@vendor/kartik-v/yii2-widget-switchinput',
        '@bower' => '@vendor/bower-asset',
    ],        
];