name: shared
description: Librería compartida con código común para apps paciente y médico
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.4+2
  http: ^1.2.1
  speech_to_text: ^7.0.0
  record: ^7.1.1
  local_auth: ^3.0.2
  shared_preferences: ^2.2.2
  didit_sdk: ^4.7.1
  share_plus: ^13.3.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^22.3.0
  timezone: ^0.11.1
  firebase_core: ^4.13.0
  firebase_crashlytics: ^5.2.7
  permission_handler: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

