name: shared
description: Librería compartida con código común para apps paciente y médico
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.4+2
  http: ^1.2.1
  local_auth: ^2.1.7
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  didit_sdk: ^3.2.0
  share_plus: ^10.1.4
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/

