<?php

namespace common\components\Domain\Scheduling\Agenda\Domain\Catalog;

/**
 * Catálogo de dominio (ex Scheduling/metadata/reserva_triage_catalog_v1.yaml).
 */
final class ReservaTriageCatalog
{
    /**
     * @return array<string, mixed>
     */
    public static function config(): array
    {
        return [
        'version' => 1,
        'halt_message_band_a' => 'Por lo que indicaste, conviene atención urgente ahora (guardia o emergencias). No sigas con la reserva en la app. Si empeorás, llamá al 107.',
        'steps' => [
            'raiz' => [
                'title' => '¿Qué necesitás?',
                'draft_field' => 'triage_raiz',
            ],
            'zona' => [
                'title' => '¿Qué tipo de malestar es?',
                'draft_field' => 'triage_zona',
            ],
        ],
        'nodes' => [
            0 => [
                'code' => 'malestar_nuevo',
                'step' => 'raiz',
                'label' => 'Malestar nuevo',
                'urgency_band' => 'C',
            ],
            1 => [
                'code' => 'estudio_pedido',
                'step' => 'raiz',
                'label' => 'Estudio o práctica',
                'urgency_band' => 'C',
            ],
            2 => [
                'code' => 'seguimiento_cronico',
                'step' => 'raiz',
                'label' => 'Control/Seguimiento',
                'urgency_band' => 'C',
            ],
            3 => [
                'code' => 'urgencia',
                'step' => 'raiz',
                'label' => 'Urgencia',
                'urgency_band' => 'A',
                'halts_booking' => true,
            ],
            4 => [
                'code' => 'zona_cabeza_cuello',
                'step' => 'zona',
                'parent' => 'malestar_nuevo',
                'label' => 'Cabeza, cuello o mareos',
                'match_keywords' => [
                    0 => 'cabeza',
                    1 => 'cuello',
                    2 => 'mareo',
                    3 => 'vértigo',
                    4 => 'vertigo',
                    5 => 'migraña',
                    6 => 'migrana',
                    7 => 'jaqueca',
                    8 => 'nuca',
                ],
            ],
            5 => [
                'code' => 'zona_pecho',
                'step' => 'zona',
                'parent' => 'malestar_nuevo',
                'label' => 'Pecho, corazón o respiración',
                'match_keywords' => [
                    0 => 'pecho',
                    1 => 'corazón',
                    2 => 'corazon',
                    3 => 'respira',
                    4 => 'pulmon',
                    5 => 'pulmón',
                    6 => 'tos',
                    7 => 'ahogo',
                    8 => 'taquicardia',
                ],
            ],
            6 => [
                'code' => 'zona_abdomen',
                'step' => 'zona',
                'parent' => 'malestar_nuevo',
                'label' => 'Panza, digestión o náuseas',
                'match_keywords' => [
                    0 => 'panza',
                    1 => 'abdomen',
                    2 => 'estómago',
                    3 => 'estomago',
                    4 => 'digestión',
                    5 => 'digestion',
                    6 => 'náusea',
                    7 => 'nausea',
                    8 => 'vómito',
                    9 => 'vomito',
                    10 => 'diarrea',
                    11 => 'intestin',
                ],
            ],
            7 => [
                'code' => 'zona_musculoesqueletico',
                'step' => 'zona',
                'parent' => 'malestar_nuevo',
                'label' => 'Espalda, huesos, músculos o articulaciones',
                'match_keywords' => [
                    0 => 'espalda',
                    1 => 'columna',
                    2 => 'hueso',
                    3 => 'músculo',
                    4 => 'musculo',
                    5 => 'articulac',
                    6 => 'rodilla',
                    7 => 'tobillo',
                    8 => 'hombro',
                    9 => 'cadera',
                    10 => 'cintura',
                    11 => 'lumbar',
                    12 => 'cervical',
                    13 => 'fractura',
                    14 => 'esguince',
                ],
            ],
            8 => [
                'code' => 'zona_piel',
                'step' => 'zona',
                'parent' => 'malestar_nuevo',
                'label' => 'Piel (sarpullido, herida, etc.)',
                'match_keywords' => [
                    0 => 'piel',
                    1 => 'sarpullido',
                    2 => 'erupción',
                    3 => 'erupcion',
                    4 => 'herida',
                    5 => 'quemadura',
                    6 => 'roncha',
                    7 => 'picazón',
                    8 => 'picazon',
                    9 => 'eczema',
                    10 => 'psoriasis',
                ],
            ],
            9 => [
                'code' => 'zona_sistemas',
                'step' => 'zona',
                'parent' => 'malestar_nuevo',
                'label' => 'Ojos, boca o dientes',
                'match_keywords' => [
                    0 => 'ojo',
                    1 => 'vista',
                    2 => 'visión',
                    3 => 'vision',
                    4 => 'diente',
                    5 => 'muela',
                    6 => 'boca',
                    7 => 'dental',
                    8 => 'oído',
                    9 => 'oido',
                    10 => 'garganta',
                ],
            ],
            10 => [
                'code' => 'zona_genitourinario',
                'step' => 'zona',
                'parent' => 'malestar_nuevo',
                'label' => 'Ginecológico, embarazo o urinario',
                'match_keywords' => [
                    0 => 'embaraz',
                    1 => 'semanas de gestac',
                    2 => 'semanas y sangr',
                    3 => 'parto',
                    4 => 'gineco',
                    5 => 'útero',
                    6 => 'utero',
                    7 => 'ovario',
                    8 => 'menstrua',
                    9 => 'regla',
                    10 => 'vagina',
                    11 => 'vulva',
                    12 => 'flujo vaginal',
                    13 => 'mamografia',
                    14 => 'mamografía',
                    15 => 'próstata',
                    16 => 'prostata',
                    17 => 'orina',
                    18 => 'urina',
                    19 => 'vejiga',
                ],
            ],
            11 => [
                'code' => 'zona_general',
                'step' => 'zona',
                'parent' => 'malestar_nuevo',
                'label' => 'Síntoma general (fiebre, cansancio u otro)',
                'match_keywords' => [
                    0 => 'fiebre',
                    1 => 'cansancio',
                    2 => 'fatiga',
                    3 => 'decaimiento',
                    4 => 'malestar general',
                    5 => 'ansioso',
                    6 => 'ansiedad',
                    7 => 'insomnio',
                    8 => 'no puedo dormir',
                    9 => 'depresión',
                    10 => 'depresion',
                    11 => 'salud mental',
                ],
            ],
        ],
    ];
    }
}
